export const profile = {
  name: "Sifat Hossain",
  title: "Web3 & DeFi Developer",
  subtitle: "Multi-Chain Builder",
  tagline: "Building decentralized applications across Monad, Sui, Aptos, Solana, Base & Arc",
  bio: "Focused on DeFi protocols, stablecoin systems, and multi-chain infrastructure. Currently building across Monad, Sui, Aptos, Base, and Arc testnets. I work with TypeScript, Next.js, Solidity, and modern Web3 tooling. Exploring cross-chain interoperability, on-chain gaming, and AI-powered dApps.",
  location: "Asia/Dhaka (UTC+6)",
  email: "sifathossain551@gmail.com",
  twitter: "Sifat551",
  twitterUrl: "https://x.com/Sifat551",
  github: "SifatHossain456",
  githubUrl: "https://github.com/SifatHossain456",
  avatar: "https://avatars.githubusercontent.com/u/53669494?v=4",
  followers: 2,
  following: 11,
  publicRepos: 57,
  publicGists: 1,
  createdAt: "2019-08-04",
  quote: "Always building, always shipping — one chain at a time.",
};

export type Project = {
  name: string;
  slug: string;
  description: string;
  longDescription?: string;
  url: string;
  homepage?: string;
  stars: number;
  language: string;
  languages: string[];
  topics: string[];
  category: string;
  featured: boolean;
  createdAt: string;
  updatedAt: string;
  highlights?: string[];
};

export const projects: Project[] = [
  {
    name: "Arc Nova",
    slug: "arc-nova",
    description: "DeFi hub for the Arc Network — swap, stake, borrow, and track your Arc portfolio in one unified interface.",
    longDescription: "A full-featured DeFi hub for the Arc Network combining swap, staking, borrowing, and portfolio tracking into a single unified interface. The flagship project of the Arc ecosystem.",
    url: "https://github.com/SifatHossain456/Arc-nova",
    homepage: "https://arcnovaai.xyz/",
    stars: 1,
    language: "HTML",
    languages: ["HTML", "JavaScript", "CSS", "Solidity", "PowerShell"],
    topics: ["defi", "arc-network", "swap", "stake", "portfolio"],
    category: "DeFi",
    featured: true,
    createdAt: "2026-05-14",
    updatedAt: "2026-07-20",
    highlights: ["Unified DeFi interface", "Swap + Stake + Borrow", "Live portfolio tracking"],
  },
  {
    name: "Base Arena",
    slug: "base-arena",
    description: "On-chain prediction tournament on Base — battle other traders in real-time price prediction rounds with ETH stakes.",
    url: "https://github.com/SifatHossain456/Base-arena",
    homepage: "https://base-arena-sandy.vercel.app",
    stars: 1,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "CSS", "JavaScript"],
    topics: ["base", "prediction", "gaming", "solidity"],
    category: "Gaming",
    featured: true,
    createdAt: "2026-05-15",
    updatedAt: "2026-06-19",
    highlights: ["Real-time tournaments", "ETH stakes", "Price prediction"],
  },
  {
    name: "Base Wave",
    slug: "base-wave",
    description: "DeFi command center for Base — track live yields, discover protocols, manage your on-chain portfolio, and explore NFT collections.",
    url: "https://github.com/SifatHossain456/Base-wave",
    homepage: "https://base-wave.vercel.app",
    stars: 1,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "CSS", "JavaScript"],
    topics: ["base", "defi", "portfolio", "nft", "yields"],
    category: "DeFi",
    featured: true,
    createdAt: "2026-05-15",
    updatedAt: "2026-06-07",
    highlights: ["Live yield tracking", "Protocol discovery", "NFT exploration"],
  },
  {
    name: "LendX",
    slug: "lendx",
    description: "Collateralized lending protocol — supply WETH, borrow USDC, health factor, and liquidation on Base Sepolia.",
    url: "https://github.com/SifatHossain456/LendX",
    homepage: "https://lendx-protocol.vercel.app",
    stars: 0,
    language: "Solidity",
    languages: ["Solidity", "TypeScript", "JavaScript", "CSS"],
    topics: ["base", "defi", "health-factor", "lending", "liquidation", "nextjs", "wagmi", "web3"],
    category: "DeFi",
    featured: true,
    createdAt: "2026-06-07",
    updatedAt: "2026-06-08",
    highlights: ["Health factor system", "Liquidation engine", "Collateralized borrowing"],
  },
  {
    name: "AMMX",
    slug: "ammx",
    description: "Constant Product AMM on Base Sepolia — x*y=k, LP tokens, 0.3% swap fee, and price impact calculations.",
    url: "https://github.com/SifatHossain456/AMMX",
    homepage: "https://ammx-dex.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["amm", "base-sepolia", "defi", "nextjs", "solidity", "uniswap", "wagmi"],
    category: "DeFi",
    featured: true,
    createdAt: "2026-06-08",
    updatedAt: "2026-06-09",
    highlights: ["x*y=k AMM", "LP token system", "0.3% swap fee"],
  },
  {
    name: "YieldX",
    slug: "yieldx",
    description: "ERC4626 tokenized yield vault — deposit USDC, receive yvUSDC shares, earn yield as share price appreciates on Base Sepolia.",
    url: "https://github.com/SifatHossain456/YieldX",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["base", "defi", "erc4626", "nextjs", "rainbowkit", "solidity", "wagmi", "yield-vault"],
    category: "DeFi",
    featured: true,
    createdAt: "2026-06-08",
    updatedAt: "2026-06-08",
    highlights: ["ERC4626 standard", "Share-price yield", "RainbowKit integration"],
  },
  {
    name: "AuctionX",
    slug: "auctionx",
    description: "Dutch Auction Token Sale — linear price decay, commit-then-claim pattern, 5-state machine on Base Sepolia.",
    url: "https://github.com/SifatHossain456/AuctionX",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["base-sepolia", "blockchain", "defi", "dutch-auction", "erc20", "nextjs", "solidity", "wagmi"],
    category: "DeFi",
    featured: false,
    createdAt: "2026-06-08",
    updatedAt: "2026-06-09",
    highlights: ["Dutch auction mechanism", "5-state machine", "Linear price decay"],
  },
  {
    name: "MultiSigX",
    slug: "multisigx",
    description: "Gnosis Safe-inspired M-of-N multi-signature wallet on Base Sepolia with threshold approval.",
    url: "https://github.com/SifatHossain456/MultiSigX",
    homepage: "https://multisigx-wallet.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["base-sepolia", "defi", "gnosis-safe", "multisig", "nextjs", "solidity"],
    category: "Infrastructure",
    featured: false,
    createdAt: "2026-06-09",
    updatedAt: "2026-06-09",
    highlights: ["M-of-N threshold", "Gnosis Safe inspired", "On-chain execution"],
  },
  {
    name: "FlashX",
    slug: "flashx",
    description: "ERC3156 zero-collateral flash loan protocol — borrow any amount, use funds, return in one atomic transaction.",
    url: "https://github.com/SifatHossain456/FlashX",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["base-sepolia", "defi", "erc3156", "flash-loans", "nextjs", "solidity"],
    category: "DeFi",
    featured: false,
    createdAt: "2026-06-09",
    updatedAt: "2026-06-09",
    highlights: ["ERC3156 standard", "Zero collateral", "Atomic transactions"],
  },
  {
    name: "StreamX",
    slug: "streamx",
    description: "Payment streaming protocol (Sablier v1 style) — per-second linear streams, withdraw anytime on Base Sepolia.",
    url: "https://github.com/SifatHossain456/StreamX",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["base-sepolia", "defi", "nextjs", "sablier", "solidity", "streaming"],
    category: "DeFi",
    featured: false,
    createdAt: "2026-06-09",
    updatedAt: "2026-06-09",
    highlights: ["Per-second streaming", "Sablier v1 style", "Linear release"],
  },
  {
    name: "CoinX",
    slug: "coinx",
    description: "MakerDAO-style CDP stablecoin on Base Sepolia — collateralized debt positions.",
    url: "https://github.com/SifatHossain456/CoinX",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["base-sepolia", "cdp", "defi", "makerdao", "solidity", "stablecoin"],
    category: "DeFi",
    featured: false,
    createdAt: "2026-06-09",
    updatedAt: "2026-06-09",
    highlights: ["CDP mechanism", "MakerDAO style", "Stablecoin issuance"],
  },
  {
    name: "TrustLock",
    slug: "trustlock",
    description: "Token vesting and escrow protocol — cliff + linear release schedules, trustless fund locking on Base Sepolia.",
    url: "https://github.com/SifatHossain456/TrustLock",
    homepage: "https://trustlock-base.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["vesting", "escrow", "base", "defi"],
    category: "Infrastructure",
    featured: false,
    createdAt: "2026-06-07",
    updatedAt: "2026-06-08",
    highlights: ["Cliff + linear vesting", "Trustless escrow", "Beneficiary claims"],
  },
  {
    name: "MultiSafe",
    slug: "multisafe",
    description: "Multi-signature wallet — threshold-based transaction approval, ECDSA signature verification, and on-chain execution.",
    url: "https://github.com/SifatHossain456/MultiSafe",
    homepage: "https://multisafe-base.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["multisig", "ecdsa", "base", "defi"],
    category: "Infrastructure",
    featured: false,
    createdAt: "2026-06-06",
    updatedAt: "2026-06-07",
    highlights: ["ECDSA verification", "Threshold approval", "On-chain execution"],
  },
  {
    name: "DropForge",
    slug: "dropforge",
    description: "ERC20 token airdrop platform with Merkle proof claims — create campaigns, whitelist recipients, distribute tokens.",
    url: "https://github.com/SifatHossain456/DropForge",
    homepage: "https://dropforge-base.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["airdrop", "merkle-proof", "erc20", "base"],
    category: "Infrastructure",
    featured: false,
    createdAt: "2026-06-07",
    updatedAt: "2026-06-07",
    highlights: ["Merkle proof claims", "Campaign creation", "Whitelist management"],
  },
  {
    name: "StakeVault",
    slug: "stakevault",
    description: "Staking vault protocol on Base Sepolia with reward distribution.",
    url: "https://github.com/SifatHossain456/StakeVault",
    homepage: "https://stakevault-base.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["staking", "base", "defi"],
    category: "DeFi",
    featured: false,
    createdAt: "2026-06-07",
    updatedAt: "2026-06-07",
  },
  {
    name: "NexMint",
    slug: "nexmint",
    description: "NFT Launchpad with ERC721, Merkle proof whitelist, phased minting, and ERC-2981 royalties on Base Sepolia.",
    url: "https://github.com/SifatHossain456/NexMint",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["base", "defi", "erc721", "merkle-proof", "nextjs", "nft", "rainbowkit", "solidity", "web3"],
    category: "NFT",
    featured: false,
    createdAt: "2026-06-07",
    updatedAt: "2026-06-07",
    highlights: ["ERC721 + ERC-2981", "Phased minting", "Merkle whitelist"],
  },
  {
    name: "GovernX",
    slug: "governx",
    description: "DAO Governance platform with ERC20Votes, Governor, and Timelock on Base Sepolia.",
    url: "https://github.com/SifatHossain456/GovernX",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["base", "dao", "defi", "erc20votes", "governance", "governor", "nextjs", "solidity", "web3"],
    category: "DAO",
    featured: false,
    createdAt: "2026-06-07",
    updatedAt: "2026-06-07",
    highlights: ["ERC20Votes", "Governor + Timelock", "On-chain voting"],
  },
  {
    name: "ChainPass",
    slug: "chainpass",
    description: "x402 micropayment content platform on Base — pay-per-access crypto guides unlocked with ETH using the x402 payment protocol.",
    url: "https://github.com/SifatHossain456/ChainPass",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "JavaScript", "CSS"],
    topics: ["x402", "micropayment", "base", "content"],
    category: "Infrastructure",
    featured: false,
    createdAt: "2026-06-06",
    updatedAt: "2026-06-07",
    highlights: ["x402 protocol", "Pay-per-access", "ETH micropayments"],
  },
  {
    name: "StakePad",
    slug: "stakepad",
    description: "Synthetix-style staking rewards — stake STKN, earn RWRD, rewardPerToken accumulator for O(1) distribution, live APR.",
    url: "https://github.com/SifatHossain456/StakePad",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["synthetix", "staking", "rewards", "base"],
    category: "DeFi",
    featured: false,
    createdAt: "2026-06-06",
    updatedAt: "2026-06-07",
    highlights: ["O(1) distribution", "rewardPerToken accumulator", "Live APR"],
  },
  {
    name: "MemoryChain",
    slug: "memorychain",
    description: "On-chain memory card matching game on Base — flip cards, find pairs, record high scores on the blockchain.",
    url: "https://github.com/SifatHossain456/MemoryChain",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "CSS", "JavaScript"],
    topics: ["game", "base", "on-chain"],
    category: "Gaming",
    featured: false,
    createdAt: "2026-06-06",
    updatedAt: "2026-06-07",
  },
  {
    name: "ArrowChain",
    slug: "arrowchain",
    description: "On-chain arrow puzzle game on Base — remove arrows in the correct sequence to clear the board and set records on-chain.",
    url: "https://github.com/SifatHossain456/ArrowChain",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "CSS", "JavaScript"],
    topics: ["game", "puzzle", "base", "on-chain"],
    category: "Gaming",
    featured: false,
    createdAt: "2026-06-05",
    updatedAt: "2026-06-07",
  },
  {
    name: "SwapX",
    slug: "swapx",
    description: "AMM DEX on Base Sepolia — constant-product formula (x·y=k), LP tokens, 0.3% swap fee, Babylonian sqrt, single-click liquidity.",
    url: "https://github.com/SifatHossain456/SwapX",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["amm", "dex", "base", "defi"],
    category: "DeFi",
    featured: false,
    createdAt: "2026-06-05",
    updatedAt: "2026-06-07",
    highlights: ["x·y=k formula", "Babylonian sqrt", "Single-click liquidity"],
  },
  {
    name: "FundFlow",
    slug: "fundflow",
    description: "Decentralized crowdfunding on Base Sepolia — create campaigns, contribute ETH, auto-refund if goal not met, pull-pattern withdrawals.",
    url: "https://github.com/SifatHossain456/FundFlow",
    homepage: "https://fund-flow-kappa-indol.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["crowdfunding", "base", "defi"],
    category: "DeFi",
    featured: false,
    createdAt: "2026-06-04",
    updatedAt: "2026-06-07",
    highlights: ["Auto-refund mechanism", "Pull-pattern withdrawals", "Campaign goals"],
  },
  {
    name: "CoinPulse",
    slug: "coinpulse",
    description: "Real-time crypto market intelligence — live heatmap, fear and greed gauge, portfolio tracker, watchlist, BTC chart, DeFi TVL and top 100 coins.",
    url: "https://github.com/SifatHossain456/CoinPulse",
    homepage: "https://coinpulse-crypto.vercel.app",
    stars: 0,
    language: "JavaScript",
    languages: ["JavaScript", "HTML", "CSS"],
    topics: ["coingecko", "crypto", "dashboard", "defi", "market-data", "portfolio"],
    category: "Market Intelligence",
    featured: true,
    createdAt: "2026-06-03",
    updatedAt: "2026-06-03",
    highlights: ["Fear & Greed gauge", "Live heatmap", "Portfolio tracker"],
  },
  {
    name: "TradeLog",
    slug: "tradelog",
    description: "Crypto trading journal with P&L tracking, win rate, profit factor, equity curve, live prices via CoinGecko API.",
    url: "https://github.com/SifatHossain456/TradeLog",
    homepage: "https://tradelog-crypto.vercel.app",
    stars: 0,
    language: "JavaScript",
    languages: ["JavaScript", "HTML", "CSS"],
    topics: ["coingecko", "crypto", "finance", "journal", "pnl", "trading"],
    category: "Market Intelligence",
    featured: false,
    createdAt: "2026-06-03",
    updatedAt: "2026-06-03",
    highlights: ["P&L tracking", "Equity curve", "Win rate analytics"],
  },
  {
    name: "DrawPad",
    slug: "drawpad",
    description: "Online canvas drawing app — pen, brush, shapes, text tool, layers system, eyedropper, zoom, undo/redo, PNG export.",
    url: "https://github.com/SifatHossain456/-DrawPad",
    homepage: "https://drawpad-coral.vercel.app",
    stars: 0,
    language: "JavaScript",
    languages: ["JavaScript", "HTML", "CSS"],
    topics: ["canvas", "creative", "drawing-app", "layers", "web-app"],
    category: "Productivity",
    featured: false,
    createdAt: "2026-06-02",
    updatedAt: "2026-06-03",
    highlights: ["Layers system", "Multi-tool canvas", "PNG export"],
  },
  {
    name: "Spendly",
    slug: "spendly",
    description: "Personal expense tracker — income/expense CRUD, category breakdown, monthly overview charts, filter/sort, localStorage persistence.",
    url: "https://github.com/SifatHossain456/Spendly",
    homepage: "https://spendly-sable.vercel.app",
    stars: 0,
    language: "JavaScript",
    languages: ["JavaScript", "CSS", "HTML"],
    topics: ["chartjs", "charts", "expense-tracker", "finance"],
    category: "Productivity",
    featured: false,
    createdAt: "2026-06-02",
    updatedAt: "2026-06-03",
  },
  {
    name: "Splyt",
    slug: "splyt",
    description: "On-chain bill splitting on Base — create a split, share a link, let friends pay their share in ETH trustlessly.",
    url: "https://github.com/SifatHossain456/Splyt",
    homepage: "https://splyt-dun.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "JavaScript", "CSS"],
    topics: ["bill-split", "base", "defi"],
    category: "DeFi",
    featured: false,
    createdAt: "2026-06-02",
    updatedAt: "2026-06-07",
  },
  {
    name: "Lens",
    slug: "lens",
    description: "AI-powered wallet reputation scorer on Base — Basescan activity analysis with 5-dimension scoring: volume, diversity, age, DeFi, NFT.",
    url: "https://github.com/SifatHossain456/Lens",
    homepage: "https://lens-one-sigma.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "JavaScript", "CSS"],
    topics: ["ai", "reputation", "base", "scoring"],
    category: "AI",
    featured: true,
    createdAt: "2026-06-01",
    updatedAt: "2026-06-07",
    highlights: ["5-dimension scoring", "AI-powered analysis", "Basescan integration"],
  },
  {
    name: "Flux",
    slug: "flux",
    description: "AI-powered Base chain wallet dashboard — real-time portfolio via Base MCP, token balances, transaction history, and chain analytics.",
    url: "https://github.com/SifatHossain456/Flux",
    homepage: "https://flux-lac-six.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "JavaScript", "CSS"],
    topics: ["ai", "base", "wallet", "dashboard", "mcp"],
    category: "AI",
    featured: true,
    createdAt: "2026-06-01",
    updatedAt: "2026-06-07",
    highlights: ["Base MCP integration", "AI-powered analytics", "Real-time portfolio"],
  },
  {
    name: "CryptoScope",
    slug: "cryptoscope",
    description: "Live crypto market dashboard — real-time prices, heatmap, Fear & Greed index, and sparklines for 100+ coins via CoinGecko.",
    url: "https://github.com/SifatHossain456/cryptoscope",
    homepage: "https://cryptoscope-zeta.vercel.app",
    stars: 0,
    language: "JavaScript",
    languages: ["JavaScript", "CSS"],
    topics: ["coingecko", "crypto", "dashboard", "market-data"],
    category: "Market Intelligence",
    featured: false,
    createdAt: "2026-05-21",
    updatedAt: "2026-06-07",
  },
  {
    name: "Nova Learn",
    slug: "nova-learn",
    description: "Learn DeFi by building it — three focused Solidity lessons covering ERC20 tokens, staking, and AMM mechanics with hands-on code.",
    url: "https://github.com/SifatHossain456/nova-learn",
    homepage: "https://nova-learn-sigma.vercel.app",
    stars: 0,
    language: "Solidity",
    languages: ["Solidity", "JavaScript", "HTML"],
    topics: ["education", "defi", "solidity", "erc20", "staking", "amm"],
    category: "Education",
    featured: false,
    createdAt: "2026-05-30",
    updatedAt: "2026-06-07",
    highlights: ["Hands-on Solidity", "ERC20 + Staking + AMM", "Learn by building"],
  },
  {
    name: "VaultBridge",
    slug: "vaultbridge",
    description: "Cross-chain bridge UI — transfer assets between ETH, Base, Arbitrum, Polygon, and Optimism with a clean multi-chain interface.",
    url: "https://github.com/SifatHossain456/VaultBridge",
    homepage: "https://vault-bridge-alpha.vercel.app",
    stars: 0,
    language: "JavaScript",
    languages: ["JavaScript", "CSS"],
    topics: ["bridge", "cross-chain", "defi"],
    category: "Infrastructure",
    featured: false,
    createdAt: "2026-05-22",
    updatedAt: "2026-06-07",
  },
  {
    name: "NaxusAI",
    slug: "naxusai",
    description: "Multi-model AI chat interface — stream responses from Claude Haiku, Sonnet, and Opus with model switching and conversation history.",
    url: "https://github.com/SifatHossain456/NaxusAI",
    homepage: "https://naxus-ai.vercel.app",
    stars: 0,
    language: "JavaScript",
    languages: ["JavaScript", "CSS"],
    topics: ["ai", "claude", "chat", "streaming"],
    category: "AI",
    featured: true,
    createdAt: "2026-05-23",
    updatedAt: "2026-06-07",
    highlights: ["Multi-model switching", "Claude Haiku/Sonnet/Opus", "Streaming responses"],
  },
  {
    name: "GovChain",
    slug: "govchain",
    description: "DAO governance platform — create on-chain proposals, vote with token weight, and execute passed decisions via timelock.",
    url: "https://github.com/SifatHossain456/GovChain",
    homepage: "https://kanban-flow-y5c6.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "CSS"],
    topics: ["dao", "governance", "proposals", "voting", "timelock"],
    category: "DAO",
    featured: false,
    createdAt: "2026-05-23",
    updatedAt: "2026-06-07",
  },
  {
    name: "KanbanFlow",
    slug: "kanbanflow",
    description: "Productivity tool — organize projects with drag-and-drop task management, streamlined workflows, and persistent data storage.",
    url: "https://github.com/SifatHossain456/KanbanFlow",
    homepage: "https://kanban-flow-neon.vercel.app",
    stars: 0,
    language: "JavaScript",
    languages: ["JavaScript", "CSS"],
    topics: ["kanban", "productivity", "drag-and-drop"],
    category: "Productivity",
    featured: false,
    createdAt: "2026-05-23",
    updatedAt: "2026-06-02",
  },
  {
    name: "MintWatch",
    slug: "mintwatch",
    description: "NFT launch calendar — discover upcoming mint dates, track release schedules, and never miss a drop across major collections.",
    url: "https://github.com/SifatHossain456/mintwatch",
    homepage: "https://mintwatch.vercel.app",
    stars: 0,
    language: "JavaScript",
    languages: ["JavaScript", "CSS"],
    topics: ["nft", "calendar", "mint", "drops"],
    category: "NFT",
    featured: false,
    createdAt: "2026-05-21",
    updatedAt: "2026-06-07",
  },
  {
    name: "ChainViz",
    slug: "chainviz",
    description: "Live block visualizer — watch new blocks appear as they are mined in real time with transaction counts and gas metrics.",
    url: "https://github.com/SifatHossain456/chainviz-",
    homepage: "https://chainviz.vercel.app",
    stars: 0,
    language: "JavaScript",
    languages: ["JavaScript", "CSS"],
    topics: ["blockchain", "visualizer", "real-time"],
    category: "Market Intelligence",
    featured: false,
    createdAt: "2026-05-20",
    updatedAt: "2026-06-07",
  },
  {
    name: "DexPulse",
    slug: "dex-pulse",
    description: "Real-time DEX wallet intelligence — track token movements, swap history, and wallet activity across multiple chains.",
    url: "https://github.com/SifatHossain456/dex-pulse",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "CSS"],
    topics: ["dex", "wallet", "intelligence", "multi-chain"],
    category: "Market Intelligence",
    featured: false,
    createdAt: "2026-05-20",
    updatedAt: "2026-06-07",
  },
  {
    name: "WalletX",
    slug: "walletx",
    description: "Cross-chain wallet intelligence platform — aggregate balances, NFTs, transaction history, and performance data across multiple networks.",
    url: "https://github.com/SifatHossain456/walletx",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "CSS"],
    topics: ["wallet", "multi-chain", "nft", "analytics"],
    category: "Infrastructure",
    featured: false,
    createdAt: "2026-05-20",
    updatedAt: "2026-06-07",
  },
  {
    name: "NFT Pulse",
    slug: "nft-pulse",
    description: "Trending NFT tracker — top collections ranked by 24h volume with floor price, sales count, and market cap analytics.",
    url: "https://github.com/SifatHossain456/nft-pulse",
    homepage: "https://nft-pulse.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "JavaScript", "CSS"],
    topics: ["nft", "trending", "analytics", "floor-price"],
    category: "NFT",
    featured: false,
    createdAt: "2026-05-19",
    updatedAt: "2026-06-07",
  },
  {
    name: "Neon",
    slug: "neon",
    description: "Multi-chain DeFi dashboard — real-time analytics across Monad, Sui, Aptos, Solana, and Arc networks with live portfolio tracking.",
    url: "https://github.com/SifatHossain456/Neon",
    homepage: "https://neon-ten-xi.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "JavaScript", "CSS"],
    topics: ["multi-chain", "dashboard", "monad", "sui", "aptos", "solana", "arc"],
    category: "Infrastructure",
    featured: true,
    createdAt: "2026-05-16",
    updatedAt: "2026-06-07",
    highlights: ["5-chain analytics", "Real-time TPS", "Live portfolio tracking"],
  },
  {
    name: "DeFi Radar",
    slug: "defi-radar",
    description: "Real-time DeFi market intelligence — track protocol TVL, yield opportunities, token flows, and on-chain activity across major protocols.",
    url: "https://github.com/SifatHossain456/defi-radar",
    homepage: "https://defi-radar-three.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "JavaScript", "CSS"],
    topics: ["defi", "tvl", "yields", "market-intelligence"],
    category: "Market Intelligence",
    featured: false,
    createdAt: "2026-05-18",
    updatedAt: "2026-06-07",
  },
  {
    name: "SportsFlex",
    slug: "sportsflex",
    description: "Sports news and fixtures tracker with live scores, league tables, and match highlights.",
    url: "https://github.com/SifatHossain456/SportsFlex",
    homepage: "https://sports-flex-five.vercel.app",
    stars: 0,
    language: "JavaScript",
    languages: ["JavaScript", "HTML", "CSS"],
    topics: ["sports", "live-scores", "fixtures"],
    category: "Productivity",
    featured: false,
    createdAt: "2026-05-25",
    updatedAt: "2026-06-06",
  },
  {
    name: "Rialo Syncred",
    slug: "rialo-syncred",
    description: "Async lending protocol demo on Goerli — Rialo-style deferred execution, collateral management, and async loan settlement.",
    url: "https://github.com/SifatHossain456/Rialo-Syncred",
    homepage: "https://rialo-syncred.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["async", "lending", "rialo", "defi"],
    category: "DeFi",
    featured: false,
    createdAt: "2026-05-16",
    updatedAt: "2026-06-07",
  },
  {
    name: "Arc Core",
    slug: "arc-core",
    description: "Stablecoin payments dApp on Arc Testnet — send, request, and track USDC payments with a clean wagmi + RainbowKit interface.",
    url: "https://github.com/SifatHossain456/Arc-Core",
    homepage: "https://arc-core.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "CSS", "JavaScript"],
    topics: ["arc", "payments", "stablecoin", "wagmi", "rainbowkit"],
    category: "DeFi",
    featured: false,
    createdAt: "2026-05-16",
    updatedAt: "2026-06-07",
  },
  {
    name: "Rialo Spars Game",
    slug: "rialo-spars-game",
    description: "Spars battle game built on Rialo network — on-chain PvP combat with async execution.",
    url: "https://github.com/SifatHossain456/Rialo-spars-game",
    homepage: "https://rialo-spars-game.vercel.app",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "CSS", "JavaScript"],
    topics: ["game", "pvp", "rialo", "async"],
    category: "Gaming",
    featured: false,
    createdAt: "2026-05-17",
    updatedAt: "2026-06-06",
  },
  {
    name: "Rialo Car Game",
    slug: "rialo-car-game",
    description: "On-chain car racing game on Rialo network with async game state execution.",
    url: "https://github.com/SifatHossain456/rialo-car-game",
    stars: 1,
    language: "HTML",
    languages: ["HTML"],
    topics: ["game", "racing", "rialo", "on-chain"],
    category: "Gaming",
    featured: false,
    createdAt: "2025-10-05",
    updatedAt: "2026-06-06",
  },
  {
    name: "BondX",
    slug: "bondx",
    description: "Bond protocol on Base Sepolia with Solidity smart contracts and Next.js frontend.",
    url: "https://github.com/SifatHossain456/BondX",
    stars: 0,
    language: "TypeScript",
    languages: ["TypeScript", "Solidity", "JavaScript", "CSS"],
    topics: ["bond", "base", "defi"],
    category: "DeFi",
    featured: false,
    createdAt: "2026-06-11",
    updatedAt: "2026-06-11",
  },
];

export type SkillGroup = {
  category: string;
  icon: string;
  skills: { name: string; level: number }[];
};

export const skillGroups: SkillGroup[] = [
  {
    category: "Languages",
    icon: "Code2",
    skills: [
      { name: "TypeScript", level: 95 },
      { name: "JavaScript", level: 95 },
      { name: "Solidity", level: 90 },
      { name: "Python", level: 70 },
      { name: "HTML5", level: 90 },
      { name: "CSS3", level: 90 },
    ],
  },
  {
    category: "Frontend & Frameworks",
    icon: "Layout",
    skills: [
      { name: "Next.js", level: 95 },
      { name: "React", level: 90 },
      { name: "Tailwind CSS", level: 90 },
      { name: "Framer Motion", level: 85 },
      { name: "Three.js", level: 75 },
      { name: "Recharts", level: 80 },
    ],
  },
  {
    category: "Web3 & Blockchain",
    icon: "Link2",
    skills: [
      { name: "wagmi", level: 95 },
      { name: "Viem", level: 90 },
      { name: "RainbowKit", level: 90 },
      { name: "ethers.js", level: 85 },
      { name: "Foundry", level: 75 },
      { name: "Hardhat", level: 80 },
    ],
  },
  {
    category: "Chains & Networks",
    icon: "Network",
    skills: [
      { name: "Ethereum", level: 90 },
      { name: "Base", level: 95 },
      { name: "Solana", level: 75 },
      { name: "Monad", level: 80 },
      { name: "Sui", level: 75 },
      { name: "Aptos", level: 75 },
      { name: "Arc Network", level: 90 },
      { name: "Rialo", level: 80 },
    ],
  },
  {
    category: "DeFi Protocols",
    icon: "Coins",
    skills: [
      { name: "AMM / DEX", level: 90 },
      { name: "Lending & Borrowing", level: 90 },
      { name: "Staking & Yield", level: 90 },
      { name: "Flash Loans", level: 85 },
      { name: "Multi-sig Wallets", level: 85 },
      { name: "DAO Governance", level: 85 },
      { name: "NFT / ERC721", level: 85 },
      { name: "Token Vesting", level: 80 },
    ],
  },
  {
    category: "Tools & APIs",
    icon: "Wrench",
    skills: [
      { name: "CoinGecko API", level: 90 },
      { name: "DeFiLlama", level: 85 },
      { name: "DexScreener", level: 85 },
      { name: "OpenSea API", level: 80 },
      { name: "Anthropic SDK", level: 80 },
      { name: "Base MCP", level: 85 },
      { name: "Git & GitHub", level: 90 },
      { name: "Vercel", level: 90 },
    ],
  },
];

export type TimelineEvent = {
  date: string;
  title: string;
  description: string;
  category: string;
  icon: string;
};

export const timeline: TimelineEvent[] = [
  {
    date: "2019-08-04",
    title: "GitHub Journey Begins",
    description: "Created GitHub account and started exploring web development with JavaScript, HTML, and CSS.",
    category: "milestone",
    icon: "Rocket",
  },
  {
    date: "2025-06-29",
    title: "Exploring Web3 Wallets",
    description: "Forked Octra and wallet-gen projects to study wallet generation and cryptographic key management.",
    category: "learning",
    icon: "BookOpen",
  },
  {
    date: "2025-10-05",
    title: "First On-Chain Game",
    description: "Built Rialo Car Game — an on-chain racing game on the Rialo network with async game state execution.",
    category: "project",
    icon: "Gamepad2",
  },
  {
    date: "2026-05-14",
    title: "Arc Nova — Flagship Launch",
    description: "Launched Arc Nova, a full DeFi hub for the Arc Network featuring swap, stake, borrow, and portfolio tracking.",
    category: "milestone",
    icon: "Sparkles",
  },
  {
    date: "2026-05-15",
    title: "Base Ecosystem Expansion",
    description: "Built Base Arena (prediction tournaments) and Base Wave (DeFi command center) within 24 hours.",
    category: "milestone",
    icon: "Zap",
  },
  {
    date: "2026-05-16",
    title: "Multi-Chain Infrastructure",
    description: "Created Arc Core (stablecoin payments), Neon (multi-chain dashboard), and Rialo Syncred (async lending).",
    category: "project",
    icon: "Network",
  },
  {
    date: "2026-05-18",
    title: "DeFi Market Intelligence",
    description: "Shipped DeFi Radar — real-time protocol TVL, yield opportunities, and on-chain activity tracking.",
    category: "project",
    icon: "Radar",
  },
  {
    date: "2026-05-20",
    title: "Wallet & DEX Intelligence",
    description: "Built WalletX, DexPulse, and ChainViz for cross-chain wallet analytics and live block visualization.",
    category: "project",
    icon: "Activity",
  },
  {
    date: "2026-05-21",
    title: "NFT & Market Dashboards",
    description: "Created CryptoScope (100+ coin dashboard) and MintWatch (NFT launch calendar).",
    category: "project",
    icon: "BarChart3",
  },
  {
    date: "2026-05-23",
    title: "AI & Productivity Tools",
    description: "Launched NaxusAI (multi-model Claude chat) and KanbanFlow (drag-and-drop task management).",
    category: "project",
    icon: "Bot",
  },
  {
    date: "2026-06-01",
    title: "AI-Powered Web3 Analytics",
    description: "Built Flux (AI wallet dashboard with Base MCP) and Lens (AI wallet reputation scorer with 5-dimension scoring).",
    category: "milestone",
    icon: "Brain",
  },
  {
    date: "2026-06-04",
    title: "DeFi Protocol Series Begins",
    description: "Started building a comprehensive DeFi protocol suite: FundFlow (crowdfunding), SwapX (AMM DEX).",
    category: "project",
    icon: "Coins",
  },
  {
    date: "2026-06-06",
    title: "Staking & Gaming Protocols",
    description: "Shipped StakePad (Synthetix-style staking), MemoryChain, and ArrowChain (on-chain games).",
    category: "project",
    icon: "Trophy",
  },
  {
    date: "2026-06-07",
    title: "Major DeFi Protocol Sprint",
    description: "Built 8 protocols in one day: LendX, TrustLock, MultiSafe, DropForge, StakeVault, NexMint, GovernX, and more.",
    category: "milestone",
    icon: "Layers",
  },
  {
    date: "2026-06-08",
    title: "AMM & Yield Infrastructure",
    description: "Created AMMX (constant product AMM), YieldX (ERC4626 vault), and AuctionX (Dutch auction).",
    category: "project",
    icon: "TrendingUp",
  },
  {
    date: "2026-06-09",
    title: "Advanced DeFi Primitives",
    description: "Built MultiSigX, FlashX (ERC3156 flash loans), StreamX (payment streaming), and CoinX (CDP stablecoin).",
    category: "project",
    icon: "Shield",
  },
  {
    date: "2026-06-11",
    title: "Bond Protocol",
    description: "Shipped BondX — a bond protocol on Base Sepolia with Solidity contracts and Next.js frontend.",
    category: "project",
    icon: "Lock",
  },
  {
    date: "2026-07-20",
    title: "Portfolio Launch",
    description: "Designed and built a premium portfolio website showcasing the entire developer journey across 57 repositories.",
    category: "milestone",
    icon: "Globe",
  },
];

export const stats = {
  totalRepos: 57,
  totalStars: 8,
  totalProjects: 50,
  defiProtocols: 20,
  chainsSupported: 8,
  yearsActive: 7,
};

export const categories = [
  "All",
  "DeFi",
  "Market Intelligence",
  "Infrastructure",
  "Gaming",
  "AI",
  "NFT",
  "DAO",
  "Productivity",
  "Education",
];